### ISSUE TITLE
Add Navigation Bar on the Committees Page

### ISSUE THREAD

**Issue by vohndernet** [uclaacm/website#104]
The commitees page is both great and rather long to scroll through if you're not looking through every single committee (what if you just want to see facts about ACM-W?). We should implement some navigation, so that others can look the committee they want more easily. 

What I'm thinking of is a navigation bar (placement on the left side), where we have the committee diamonds you can click on, which will take you to the committee section. 

Some Examples
- TeachLA's [CipherSalad](https://ciphersalad.uclaacm.com/) has the functionality I had in mind, with its keys that navigate to each step. Instead of keys, though, we should use the different committee diamonds instead. 
- SoftServe's [website](https://www.softserveinc.com/en-us)'s navbar has more special effects we could consider adding, like the words that appear on-hover. 

Feel free to ask if you have any questions, or have comments!

**Comment by annaguo1012** [comment]
Possible design inspiration: https://reactjsexample.com/tag/sidebar/
