### ISSUE TITLE
Cross-committee Workshop Archive

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#117]
I [absolutely love Hack's Archive page](https://hack.uclaacm.com/archive), and I'd like to see if there's something similar we can do for the ACM website (for all committees).

We can first do an Minimum viable product (MVP):

* top-level workshop tracks (ex ACM AI Beginner track, Hack sprint)
* minimal metadata (links to materials, tags)
* content just for this year 

Then, we can slowly flesh it out to include:

* expandable dropdowns for each item in the track
* more in-depth tags with search and filter 
* multiple types of links with buttons/icons/other delimiters
* relevant officers, updated versions, etc.
* **a streamlined way to add new events and tracks** - maybe even importing from another data source (ex a file)
* back-adding events from past years

This is a good introductory ticket for data-driven pages. Some general thoughts on the supposed workflow:

1. decide a data structure to hold each event/track; feel free to ask committees/@mattxwang for suggestions
2. create some dummy data
3. create a React component that renders a simple UI element for one track
4. map the dummy data to a list of components via `.map()`
5. bop everything on to a page, and skeleton out some design!

Then, to add extra goodies:

* implement basic search and filters with `.filter().map()`
* expandable sections can be done by hand, with CSS libraries, or with a react plugin - there are many, do research on what you like the most!
* flesh out optional data structure members for extra metadata
* link together versions of a series (ex Hackschool, Hacksprint)
    * Can we go above and beyond with this? Offering sets of workshops that compliment each other (i.e. learn.py and ai beginner track).

Some things to think about your data structure:

* how do you want to keep track of committees? what about cross-committee events (ex Bruinquest, AI workshops at HOTH)
* do events in a track have to be linear (ex Hackschool), or can they be part of a general batch (ex workshops held at HOTH).
* how do we handle events we do for "external" bodies (ex Teach LA, W @ QWER Hacks)
* how can we avoid tag duplication (ex js and javascript, node and node.js). Is there a way we can standardize this data?
* how do you want to keep track of quarters? what if something spans multiple quarters?

**Comment by matthewcn56** [comment]
This seems to have some overlap with some of our other projects like [dev pathways](https://dev-pathways.netlify.app/) and [opensource](https://opensource.uclaacm.com/) with regards to documenting the projects and workshops that have been hosted by committees in the past. Would we want this to be part of the main website as well or in an addendum of the WIP history page that links to these tools?

**Comment by jainsujay02** [comment]
@matthewcn56 This issue perfectly encapsulates what I was hoping to directly add to the event calendar/re-do it. Based on our brief discussion, we can just add additional functionality (links to youtube videos, slides, repos, etc.) directly on the calendar. Combined with the dev pathway + open course, I'm inclined to think that we don't need a separate archive. What do you think?

**Comment by jainsujay02** [comment]
We decided that this ticket is pretty similar to open-source and with the updated events calender, this will not be necessary/helpful.
