### ISSUE TITLE
Teach LA text overflows to next line

### ISSUE THREAD

**Issue by alexanderqchen** [uclaacm/website#12]
Requested by Melissa
![teachla](https://user-images.githubusercontent.com/12878275/46753539-001de800-cc75-11e8-9e6f-0b958588820c.PNG)

**Comment by alexanderqchen** [comment]
I wasn't able to reproduce the error on multiple different browsers on mac or windows, so further investigation is needed.

**Comment by alexanderqchen** [comment]
Found out that this visual error occurs if you scale your text size through your operating system. This will be a little difficult to test because it is machine/OS-specific, but we should still account for it.

**Comment by malsf21** [comment]
I think we can close this issue now 😊
