### ISSUE TITLE
Remove "winter gm" page

### ISSUE THREAD

**Issue by evanzhong** [uclaacm/website#123]
Maintaining code is just as (if not more) important than writing new code. Removing legacy code, or code that's simply outdated is a difficult task, and there are many opinions on the "right" way to do so.

Due to virtual operations, I previously created a [landing page](https://acm.cs.ucla.edu/gm) for our virtual general meetings. We're now more than a quarter removed from our last general meeting. This ticket tasks you with removing the landing page or somehow archiving the code related to the page.

Things to consider
---
- What new component(s) were defined for this feature, what's reusable, what's not?
    - On that vein, should we do a "full rollback" (removing all code relation to the GM landing page)?
    - Or should we somehow further generalize and component-ize the code, document its existence, and move it to an archival part of the code base.
- What dependencies did this feature rely on? How do we roll this back? Do we need to roll it back?
    - How does your choice to the previous bullets affect your choice here about whether to roll back installed npm packages?
- How did this feature affect navigation? How can you find all references to this component / page and remove references to it?

Helpful resources
--
- Looking at [past Pull Requests](https://github.com/uclaacm/website/pulls?q=is%3Apr+gm)
- Exploring the code in `src/components/Events/GM/`

**Comment by advaithg** [comment]
I think a good solution to this would be to just archive the page and maintain the code/file while removing all references to it from the main web page. That way we can reuse the exact same page for later GMs simply by un-commenting references to it. Would that make sense or is there a problem with that idea?

**Comment by evanzhong** [comment]
> I think a good solution to this would be to just archive the page and maintain the code/file while removing all references to it from the main web page. That way we can reuse the exact same page for later GMs simply by un-commenting references to it and making some changes in content. Would that make sense or is there a problem with that idea?

This solution can definitely work! Some additional things to consider if you choose this approach
- How do we make it clear that a component or set of files is "archived"?
- How do we document how to "revive" a page if / when a future dev chooses to do so?
- What should we do about the assets (i.e. images, references to slides etc) that this component relies on.
    - How do we generalize these, since currently all the images are specific to a particular GM (i.e. Winter 2021)?

Would also love to hear @mattxwang's take

**Comment by mattxwang** [comment]
@advaithg I like your initial solution, and @evanzhong I think the points you bring up are pretty valid!

One approach we can consider:

* what other orgs often do is create a route called `archive` and place past events there, for posterity. For example, we could have `uclaacm.com/archive/w21-gm` be a route for the existing component.
* if we take the above approach, seems reasonable to me to make a folder in `components` that is called `archive`, which hosts each of those components 
* similarly, we can create an `archive` folder within `public` (or if you'd like, date-stamp the event) to make it clear that some assets shouldn't be re-used and are old 

This approach is hopefully minimal code motion, and also makes it easier for people down the road (i.e. after we all graduate) to see what we've done! The only downside is that we increase the client bundle size, though that's something we may be able to resolve with other frameworks (ex Next, Gatsby).

**Comment by advaithg** [comment]
The archive approach does make sense, but that might cause a lot of code repetition, especially since we'd have a similar page for each of the GMs that happen next year. (unless we're planning on redesigning the GM page for further GMs)

That being said - if you think it's best to keep the history of the Winter GM on the website, I think making an archive is a good idea.
However - if it isn't as important to have this, it would probably be more convenient to allow the page to be reused for further GMs instead of a new page in a similar style being created every time, then moved to the archive.

I don't think an archive is necessary for past GMs, especially since it happens almost every quarter (and we could leave the GM page up for the duration of the quarter) - but I also think it should be your call in the end - so I'll leave it up to you!
