### ISSUE TITLE
Website nav bar bug + redesign

### ISSUE THREAD

**Issue by annaguo1012** [uclaacm/website#138]
Currently while minimizing the website the window is on, at some point before the bar minimizing to a hamburger, the bar moves down and overlaps with the banner! Updating the hardcoded width at which the nav bar minimizes would help, but also a redesign of how we implement the nav bar would be helpful. 

Right now from what I can see, it's quite complicated. Maybe we can use bootstrap's NavBar component https://medium.com/swlh/responsive-navbar-using-react-bootstrap-5e0e0bd33bd6

![image](https://user-images.githubusercontent.com/59128109/117258186-8c7af200-ae01-11eb-8398-98cd3cf44987.png)

**Comment by annaguo1012** [comment]
![image](https://user-images.githubusercontent.com/59128109/117258164-838a2080-ae01-11eb-84cd-aa73fd1ba121.png)

**Comment by mattxwang** [comment]
Superseded by #246.
