### ISSUE TITLE
Implement cache busting with webpack (requested by Christina Indudhara)

### ISSUE THREAD

**Issue by alexanderqchen** [uclaacm/website#14]
## Motivation
We want to make sure users have the newest version of the website especially when important content is changed.

## Resources
https://stackoverflow.com/questions/39238163/how-can-i-make-webpack-use-a-cache-busting-suffix

## To Do
- [ ] Make sure that when the website is updated, the browser does not simply fetch the files from cache
- [ ] Make sure that if the website is not updated, the browser does get it from cache

**Comment by nkansal96** [comment]
This is implemented here: https://github.com/uclaacm/membership-portal-ui/blob/master/webpack.config.js

In addition, we can pre-gzip the files in web pack and then instruct nginx to serve static gzip files instead of gzipping on the fly
