### ISSUE TITLE
Committee sidebar cuts off logos

### ISSUE THREAD

**Issue by annaguo1012** [uclaacm/website#165]
Currently, clicking on the committees in the sidebar navigates to the appropriate part of the page, but cuts off the top half of the committee logo. We had previously addressed this with padding, but it seems like a more complex issue to fix now. It may have to do with using NavHashLinks or !important overriding.
![cut off logo](https://user-images.githubusercontent.com/59128109/120039473-cb900380-bfb9-11eb-8b4d-5f2e44e0d5fb.png)

**Comment by mattxwang** [comment]
Oh, totally dropped the ball on this but this was closed by #229 a while ago!
