### ISSUE TITLE
Clean up `committees.js`

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#180]
Now that it's summer, I think we should do something to make `committees.js` less overwhelming (in anticipation of NSO tabling).

In particular, some things to do:

* do we want to keep all the spring events here? if so, should we make it clear?
* if we don't want to keep the spring events, what do we put here instead? 
* images should have `alt` tags! no exceptions, unless you label it as a decorative image!

**Comment by mattxwang** [comment]
Let's set a soft deadline of July 10th for this - that's when we'll start advertising as part of NSO tabling!

**Comment by mattxwang** [comment]
Going to ping @advaithg since this is some feedback we got from the last NSO session!

**Comment by advaithg** [comment]
Just saw this! Will get to it tomorrow.
As of now I think we can keep the events, but change the label to be "Past Events" until we know what's gonna happen fall.

**Comment by annaguo1012** [comment]
Sounds good to me
