### ISSUE TITLE
remove postcss@8 as a dev dependency

### ISSUE THREAD

**Issue by advaithg** [uclaacm/website#186]
RIght now, this dependency exists as a stopgap to fix [this](https://github.com/vercel/next.js/issues/24882) error in next.js

To fix this, you'll probably have to resolve this error and then remove the dependency.

**Comment by mattxwang** [comment]
This is resolved in https://github.com/vercel/next.js/pull/26952; let's just wait then for the next patch bump to come out, and we can uninstall postcss@8 as a peer dep and call it a day.
