### ISSUE TITLE
standardize images to `next/image`

### ISSUE THREAD

**Issue by advaithg** [uclaacm/website#188]
Currently, a lot of images use the `img` tag, which shouldn't be done in next.js
This issue is to deal with these images and switch to `next/image`

as of now, `img` works as long as `/public` is maintained properly

While it sounds pretty simple, it's a lot more complicated than it sounds because of a bunch of stuff:

-  `next/image` breaks on deploy when the image is an svg file (not sure why)

- netlify doesn't seem to be fully working on deploys with `next/image` (see [this](https://github.com/vercel/next.js/issues/18356))

- `next/image` requires a `height` and a `width` or `layout=fill`, which makes it difficult in certain cases where we want to use the default image size

- `next/image` has some built in CSS that is difficult to override (see `committees.scss` for an example)

This can be put on hold until `next-on-netlify` is updated, as mentioned [here](https://answers.netlify.com/t/new-image-tag-not-working-on-next-js/25571)

**Comment by mattxwang** [comment]
To resolve the manual `img` tags, feel free to search for `<img />`, or 

```js
{/* eslint-disable-next-line @next/next/no-img-element */}
```
