### ISSUE TITLE
refactor the `GM` component

### ISSUE THREAD

**Issue by advaithg** [uclaacm/website#190]
Refactor the GM component to derive all of its information from props; then, make a new wrapper page that passes in the relevant information from data files, manual configuration, etc.

Right now, the GM component gets all it's data from a data file.
A better way to do this would be to wrap GM as a component in a dummy page for every new GM, which passes relevant data as props.

Refer to [this](https://github.com/uclaacm/website/pull/178#discussion_r659393346) comment on the next.js transition PR for more context.

**This should also convert the GM page to next.js, since it's currently based off react.js**

**Comment by advaithg** [comment]
closing since currently irrelevant

**Comment by mattxwang** [comment]
Not sure if this should have been closed, since this file still exists? https://github.com/uclaacm/website/blob/main/components/GM.js

**Comment by advaithg** [comment]
> Not sure if this should have been closed, since this file still exists? https://github.com/uclaacm/website/blob/main/components/GM.js

OH hm I missed that
Is that file used anywhere at all? Especially since there's a completely different page for fall GM. 
Do you think you'd want to use the old layout for future GMs?
Because if not we could simply delete the file entirely and rely on the fall GM page instead.

**Comment by mattxwang** [comment]
> Do you think you'd want to use the old layout for future GMs?

Up to you! Winter GM is coming up, so it will be you and Anna's decision on how you want to implement it.
