### ISSUE TITLE
Navbar breaks on about page at some screen widths

### ISSUE THREAD

**Issue by advaithg** [uclaacm/website#203]
If you switch to an iPad and go to the about page, the navbar overflows screen width, requiring the scroll to the right to use the menu. This doesn't happen with any of the other pages in this view.

<img width="772" alt="about page with overflowing navbar" src="https://user-images.githubusercontent.com/67539191/124864411-7b538a80-dfd6-11eb-9d4d-ba15f35c76ff.png">

**Comment by mattxwang** [comment]
Superseded by #246.
