### ISSUE TITLE
[Bug] Hack banner on /committees page is vertically off-center

### ISSUE THREAD

**Issue by evanzhong** [uclaacm/website#212]
Hack's banner is vertically off-center, shifted towards the top border.
![image](https://user-images.githubusercontent.com/23728476/126403233-586b5042-f8b4-44db-8553-552e2a1f67b5.png)

See AI's for reference
![image](https://user-images.githubusercontent.com/23728476/126403380-462c919f-1125-459a-90f1-523b71116c7c.png)

**Comment by blankon123** [comment]
i think that's because of the hack_wordmark svg file, can i take this one ?

**Comment by advaithg** [comment]
> i think that's because of the hack_wordmark svg file, can i take this one ?

Sure! Feel free to give it a shot and open a PR once you're done!

**Comment by mattxwang** [comment]
Closed by #215.
