### ISSUE TITLE
Committee Page nav-bar location hash UI bug

### ISSUE THREAD

**Issue by evanzhong** [uclaacm/website#228]
When navigating around the committees page we use location hashes. For example navigating to `/committees#studio` shows the following, with the committee graphic slightly occluded by the nav bar
![image](https://user-images.githubusercontent.com/23728476/128240364-6215aa9f-9dbb-4c7a-9ea5-57ed4db675e4.png)

This issue likely stems from the the way we style our nav-bar. Because we used fixed positioning (`position: fixed;`) the location hash based autoscroll clips part of the heading image.
![image](https://user-images.githubusercontent.com/23728476/128240796-6dee8120-1fd1-401a-adb8-3e459e0353bf.png)

**Comment by krishrahul98** [comment]
@evanzhong Hey, I have checked the issue. I think adding a simple CSS property will fix this issue.
`html {
  scroll-padding-top: 75px; 
}`

**Comment by mattxwang** [comment]
Just throwing my two cents in on `scroll-padding-top`, seems like the [caniuse](https://caniuse.com/?search=scroll-padding-top) indicates some issues with Safari compatibility - would be worth investigating. 

@krishrahul98 thanks for the suggestion! If you're interested, a pull request is more than welcome - feel free to fork and make the changes 😊

**Comment by krishrahul98** [comment]
@mattxwang I am making a request in few minutes.

**Comment by krishrahul98** [comment]
@mattxwang Check pull request #229
