### ISSUE TITLE
Reimplement the Navbar

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#246]
This PR aims to collate #121, #138, #203, and the follow-up from #245 - reimplement the Navbar to work properly, and redesign it to allow for extra pages.

From a functionality perspective, there are several core problems:

* resolve the navbar accessibility issue - the `input` tag should be within the `label`
* fix the variety of breakpoint bugs - #138 and #203 
* the `Navbar` component is still class-based, and also ties event listeners to DOM elements as part of the component lifecycle
* bonus: figure out a way to easily add more links to the navbar, and/or implement a dropdown <- we may punt this down the line if this proves too hard 

To do this, I think we need to adjust the entire `Navbar` component's logic. It should:

- [ ] be function-based
- [ ] not rely on DOM events or manipulation
- [ ] ideally, not duplicate markup - we should shift off of the CSS approach
- [ ] move the CSS to be moduled
- [ ] not have accessibility issues - beyond the one flagged by axe, we should annotate the hamburger lines with some `aria` label
- [ ] fix the link-tabbing behaviour (this may come with not duplicating the markup)
- [ ] either dynamically resize into the hamburger menu, or have a smarter breakpoint strategy

This closes all the must-haves for the related tickets!

**Comment by VeeGee-Creations** [comment]
I'm making some decent progress on this and will have a draft uploaded by tomorrow
