### ISSUE TITLE
Make media-tile component

### ISSUE THREAD

**Issue by alexanderqchen** [uclaacm/website#27]
![img_20190123_165635](https://user-images.githubusercontent.com/12878275/51649333-dee9ba80-1f38-11e9-9943-d93eaad06c14.jpg)
It's the thing that looks like a tile. Ask the website channel if you have any questions.

**Comment by evanzhong** [comment]
https://github.com/uclaacm/website/pull/73 creates components that can be refactored as general media tiles.

Issues is thus outdated, closing.
