### ISSUE TITLE
In-person Fall GM Page

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#280]
We need to prep our website for Fall GM! Writing this ticket out as @evanzhong has requested it!

We can reuse our old GM implementation after porting it to next; to see the winter '21 GM page ported over, see this draft PR: https://github.com/uclaacm/website/pull/271. Reusability is a bit tricky in terms of how the component is defined, but we can always prioritized the F21 GM over getting the old W21 GM out.

There are a couple of additions/changes that I (esp after receiving feedback from Rish & Christina) think we need:

1. I think we should change the countdown behaviour; instead of showing the new page after the countdown hits zero, I think we should just show it as soon as the information is available. We're not hiding a Zoom link / Discord link, and I think showing people the location and agenda ahead of time is helpful.
2. We should include a map of where the event is being held, and any relevant markers (ex entry, exit) on the map. @evanzhong it seems like you're working on getting a map of the Court of Sciences, so that can be an easy substitution.
3. We should link somewhere to our COVID-policy URL: https://uclaacm.com/covid
4. From Rish and Christina, we should include a subheading with:
    * "things you must bring": mask, bruincard, fully vaccinated
    * recommended: device to access slides, excitement to learn about ACM

Also, we'd need to update the relevant supporting copy & links: slides, text, etc.

**Comment by evanzhong** [comment]
In the interest of time I'm just going to hardcode everything.

Going to doing proper porting to Next.js in the PR draft you listed at a later time
