### ISSUE TITLE
internship page - make cards flippable and tabbable

### ISSUE THREAD

**Issue by advaithg** [uclaacm/website#295]
In the original design [here](https://www.figma.com/file/RQT8mBsi0U13W8cJsymV5b/Internship-Page-Mockup), the cards for committee intern to officer transition were meant to be a carousel of flippable cards.

We decided to change that to a grid of 3x3 cards (which becomes 2 columns in tablet mode, and 1 column on a phone), each of which is flippable to find the information about the intern to officer transition for each committee.
It wasn't implemented in time - so currently there's a temporary grid

To resolve this issue, you would have to
- use the images in the [cards](https://github.com/uclaacm/website/tree/main/public/images/cards) folder to make cards for each committee
- each card should be flippable to have the intern to officer transition on the back, and accessible through tabbing

One of the issues we were running into was it not working on some browsers but working on others - so make sure it works on multiple browsers!

**Comment by mattxwang** [comment]
Going to close this since we've wrapped up the cycle for this year.
