### ISSUE TITLE
Add ICPC World Finals qualification article to website

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#304]
Our ICPC team made World Finals, and Samueli [just published an article on it](https://samueli.ucla.edu/ucla-computer-science-student-team-advances-to-2021-icpc-world-finals/)! It would be great if we could add this to our news and events section, in [`data/news.js`](https://github.com/uclaacm/website/blob/main/data/news.js).

In terms of the image - I think the team image showcased as the above-the-fold in the article is fine! 

(this PR is how we added the article last time: #185 )

**Comment by vasav-prashar** [comment]
i like to work on this pls assign to me

**Comment by mattxwang** [comment]
> i like to work on this pls assign to me

Hi Vasav, go for it! Feel free to open a PR when you're ready, I can take a look.

**Comment by vasav-prashar** [comment]
sir, i just need to do changes in data/news.js?
