### ISSUE TITLE
Timezone-safe "countdown"-style element

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#339]
As I write more pages that involve showing content for a specific event, I find myself wanting to be able to show content _after_ a specific time has passed (think a countdown of sorts). I think this is an opportunity for us to write a very helpful wrapper component! I'm thinking of a component that:

1. Has a mandatory prop that represents time somehow (UNIX timestamp? JS timestamp? `moment`?)
2. Has a `placeholder` or `fallback` component prop that is rendered if the time hasn't happened yet
3. Renders its children if the time has happened yet

The advantage here is that we don't have to rewrite time-checking logic (which is notoriously frustrating), and instead provide our developers with a high-level API to toggle content.

I see this being useful for:

* town hall (the driving motivator for writing this ticket)
* GM
* possibly the internship timeline (though this is a bit more complicated)
* Tech Gala
* ...

**Comment by mattxwang** [comment]
@advaithg @annaguo1012 what do y'all think?

**Comment by mattxwang** [comment]
> just to clarify, this would have
> * a prop for the time at which the countdown ends
> * a child component prop for what to render before the time
> * another child component for what to render after the time

Not exactly - since I'm thinking of rendering the children in the "after" time, you wouldn't be able to put the "before" time content in there. I'm thinking instead of just having it as a component prop:

```jsx
<TimeRenderer time={123} fallback={<span>come back soon :))</span>}>
  <p>thanks for waiting</p>
</TimeRenderer>
```

Open to suggestions though!

> additionally, would this be displaying a timer of some sort for the time left as a countdown? (like the one on the GM page)
perhaps a prop to decide if a timer should be visible or not would also be a good idea - since for some cases we may not want a countdown timer (especially if we use it for the internship page in the future)

The timer could be passed to the prop for what to render before the time. We could separately create a reusable timer; I think a separation of concerns here is a good idea (especially since, as you point, out, we may not want a countdown timer).

**Comment by advaithg** [comment]
sounds good! sounds like the tougher part of this ticket will be the time logic then

**Comment by mattxwang** [comment]
@reginawang3495 two quick questions:

1. Is this ~ the level of difficulty that you want?
2. Is this description enough / too little / too much?

**Comment by reginawang3495** [comment]
Looks good! A tiny bit wordy but is good difficulty level :)

**Comment by reginawang3495** [comment]
And thanks for making tickets!
