### ISSUE TITLE
Add "initiatives" section to mobile navbar

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#351]
This is what the current mobile nav looks like:

![Screen Shot 2021-11-15 at 9 30 35 PM](https://user-images.githubusercontent.com/14893287/141926587-3125d4c3-ac19-4f8a-83a0-babd0a45e592.png)

I'd like to add links to the [impact](https://acm.cs.ucla.edu/impact) and [JEDI](https://acm.cs.ucla.edu/jedi) pages, under a header called "initiatives". Styling-wise, it should operate similar to the committees page, with the caveat that we want to highlight the current page if it's active, not the current committee based off of the hash.

I would start by looking at [`components/Navbar.js`](https://github.com/uclaacm/website/blob/main/components/Navbar.js)!

**Comment by mattxwang** [comment]
@reginawang3495

**Comment by reginawang3495** [comment]
> with the caveat that we want to highlight the current page if it's active, not the current committee based off of the hash.

I don’t understand

**Comment by mattxwang** [comment]
> I don’t understand

If we're on the "JEDI" page, we should highlight the link to the JEDI page; same for Impact.

**Comment by Marob-nod** [comment]
Hi ! Can I work on it ?

**Comment by Marob-nod** [comment]
Hi @reginawang3495 , I didnt know and I just did it. It is working ! :) 
Tell me if you  want me to pull a request.
![Capture d’écran du 2021-11-16 14-48-28](https://user-images.githubusercontent.com/79056820/141997212-2e167425-41d8-4ab9-a255-c4f2260d3b60.png)

**Comment by reginawang3495** [comment]
Sure, if you've already made it then that's fine, send over the pull request :)

**Comment by reginawang3495** [comment]
@Marob-nod any updates? :)
