### ISSUE TITLE
Adjust about page copy

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#352]
Something I never really got around to in the next rework was adjusting our About page. A few things stand out to me:

1. the font size is (arbitrarily) small
2. the body copy could be reworked; we:
    * host different types of events
    * can deprioritize the membership portal as a CTA, and instead have people follow us on instagram
    * now have an events page
    * can link to individual committees (and maybe explain what we do?)
3. the images are old!
4. "Leadership" could use some bottom margin + maybe a quick explanation of what they do

I think the tricky thing is that we have a lot of things to explain, but don't want to info dump. A good exercise in conciseness!

**Comment by mattxwang** [comment]
Not super comfortable making this a free-floating ticket since it requires familiarity with ACM. @annaguo1012 @advaithg

**Comment by advaithg** [comment]
Hm one thing we could do it make this a pair programming exercise with interns! That way they'd get to do the code but one of us would be there to help with the content. I think in terms of difficulty this it could be something to help interns familiarize themselves with a website page so as long as we provide content it should be fine?

**Comment by advaithg** [comment]
@mattxwang some clarifications I have before I assign this to someone
- are there any specific images you want us to use / replace that wouldn't be addressed by #313 
- when you link to individual committees, do you mean their website pages or their information on the committees page?
- do you think a 1-2 line explanation of what ACM's leadership as a whole does is enough, or would you want a more specific explanation of each role?
- could you elaborate on what you mean by different types of events? 
if you're referring to "With events such as infosessions, workshops, speaker panels, hackathons, and competitions, we cover a variety of topics including artificial intelligence, virtual reality, cybersecurity, mobile and web development, diversity initiatives, community outreach, and much more.", what would you like to change specifically?

**Comment by mattxwang** [comment]
> are there any specific images you want us to use / replace that wouldn't be addressed by [Update Carousel, About, other pages with new images #313](https://github.com/uclaacm/website/issues/313)

Hm, I'm not sure since I don't think a PR has been submitted, but I think the image to the right of "How do I get involved" could be updated to have more modern shots - esp with filled rooms, smiling people, etc.!

> when you link to individual committees, do you mean their website pages or their information on the committees page?

Let's say their information on the committees page for now.

> do you think a 1-2 line explanation of what ACM's leadership as a whole does is enough, or would you want a more specific explanation of each role?

1-2 line explanation total is good.

> could you elaborate on what you mean by different types of events?
>   if you're referring to "With events such as infosessions, workshops, speaker panels, hackathons, and competitions, we cover a variety of topics including artificial intelligence, virtual reality, cybersecurity, mobile and web development, diversity initiatives, community outreach, and much more.", what would you like to change specifically?

Generically, we don't do VR but still do everything else, and we have more projects teams; diversity initiatives seems gramatically strange here. I would like to see more specific examples though! We can link to HOTH for hackathons, AI beginner track, etc. Basically, my gripe here is that after reading this body copy, you still don't *really* know what ACM does. I'll leave it up to you and Anna to decide on the exact copy (ofc, feel free to consult me/Evan/the marketing team), but basically I think we need a more comprehensive about page.
