### ISSUE TITLE
Remove image dependency on Teach LA website, switch to Image tag

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#371]
When I wrote the hack-y implementations for the JEDI and Impact pages, I used people's headshots from the Teach LA website when possible. While it made prototyping for me easier, this is clearly a bad thing to do (since we don't control that codebase).

So, we should move those images to our own site. On top of that, this could give us an opportunity to switch the Impact and JEDI officer cards to use the `<Image />` tag, now that we'll know what the images look like at site compile time.

## Relevant Files

Impact officers:

https://github.com/uclaacm/website/blob/fba4833bce24fd70c5e007a06f1984251f95f10e/data/impact.js#L29-L84

JEDI officers:

https://github.com/uclaacm/website/blob/fba4833bce24fd70c5e007a06f1984251f95f10e/data/jedi.js#L126-L162

**Comment by advaithg** [comment]
JEDI page images addressed with #392
