### ISSUE TITLE
Update ACM COVID Policies page with winter quarter changes

### ISSUE THREAD

**Issue by evanzhong** [uclaacm/website#375]
Changes requested to https://acm.cs.ucla.edu/covid

Change `Last major update:` to Monday December 27th, 2021

Add a bullet point to `Version history` with date Monday December 27th, 2021 and the following copy:
`updated to reflect UCLA's Remote Start to Winter Quarter`
![image](https://user-images.githubusercontent.com/23728476/147607971-8f9311c5-3afe-4191-964a-a7e4aae3f864.png)

Update embeded google doc to point to https://docs.google.com/document/d/1_s4SEFzgiN5AyfdhoT5ccXRGnnjZ7ar7O50U86jYRpQ/edit?usp=sharing

Update `Link to Google Doc` button to point to https://docs.google.com/document/d/1_s4SEFzgiN5AyfdhoT5ccXRGnnjZ7ar7O50U86jYRpQ/edit?usp=sharing

Download ACM at UCLA COVID Policies Fall 2022 as pdf and update `Link to PDF` button to point to this new PDF 
![image](https://user-images.githubusercontent.com/23728476/147608143-7650f81b-a4af-4c4a-a6e6-0dd684eeb41a.png)

**Comment by advaithg** [comment]
Should I also be changing the title to say winter 2022 instead of fall 2021?
