### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by jdliaw** [uclaacm/website#4]
### Create a contact form for people to directly write a message to us through our website.

We will add this as a link in the top navbar called "Contact"

[insert mockup of navbar]

Possibly add it to the bottom footer next to "Reach us at"
![footer](https://puu.sh/zwsxZ/3e79215db7.png)

**Mockup:**
[insert mockup of the Contact form]

-----------------------------------------------------

### Frontend

The email given by the user will be how we will reply to their message. Make sure to validate the email in the form on the client side. 

- [ ] Create form components:
       - Name
       - Email
       - Message
       - Submit Button
       - We can manually populate the email subject as "Message from UCLA ACM website" or something
- [ ] Validate input
- [ ] Success state: Display a success message and a way to send a new message
- [ ] Fail state: Display a descriptive failure message and a way to try again

### Backend

Use some API [tbd] to send an email to acm@ucla.edu

- [ ] Get form inputs from client
- [ ] Send email to acm@ucla.edu with relevant info using ___ API
- [ ] Properly handle any possible errors

API options:
- [nodemailer](https://www.npmjs.com/package/nodemailer) (npm package)
- [SendGrid](https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/nodejs.html) has a node.js library

**Comment by evanzhong** [comment]
Closing for now, awaiting website landing page redesign.
