### ISSUE TITLE
Update Font Awesome to v6

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#424]
See [Update notes for Package Managers](https://fontawesome.com/v6/docs/web/setup/upgrade/packages) and [the changelog](https://fontawesome.com/v6/docs/web/setup/upgrade/whats-changed).

**Comment by advaithg** [comment]
Dependabot seems to have made this update? I looked through the deploy preview and all the places where we've used Font Awesome in the code, and barring the icon style slightly changing - it works fine.

**Comment by mattxwang** [comment]
> Dependabot seems to have made this update? I looked through the deploy preview and all the places where we've used Font Awesome in the code, and barring the icon style slightly changing - it works fine.

Not exactly, for packages that have peer dependencies / are 'related', you want to update them in lockstep.

For example, look at 

https://github.com/uclaacm/website/blob/ebe2a430526fab1dc88d4f21fbb5a69c0cca191d/package.json#L6-L9

Currently, we have two different sets of FA icons - v6 and v5.15 - since you updated one of them but not the other. Strictly, it doesn't cause a bug, but ideally you want to do all at once.

**Comment by advaithg** [comment]
Looking at [this](https://github.com/uclaacm/website/pull/436) pull, it looks like the only difference is the Medium icon being switched to their logo from the old "M"! Do you think that's a switch that makes sense (i.e people would be able to tell that it's Medium?)

**Comment by mattxwang** [comment]
Should be fine; if anything, if they're rebranding, then we should probably respect that!
