### ISSUE TITLE
Update ACM COVID Policies page with Spring Quarter changes -2 

### ISSUE THREAD

**Issue by jainsujay02** [uclaacm/website#479]
Changes requested to `https://acm.cs.ucla.edu/covid`
<img width="993" alt="image" src="https://user-images.githubusercontent.com/78530348/162675523-20c02e60-2c2d-443e-9ddb-fb1965a91a45.png">

- [ ] Change `Last Major Update`: to Monday, April 11th, 2022

- [ ] Add a bullet point to `Version history` with the date, Monday, April 11th, 2022 and the following copy: `Updated based on UCLA's  Updates on COVID-19 Protocols for Spring Quarter`

<img width="925" alt="image" src="https://user-images.githubusercontent.com/78530348/162675993-b9c05b8b-6daf-4c8e-8d13-1eb6db75a2b8.png">

- [ ] Update embedded google doc and `Link to Google Doc` to point to https://docs.google.com/document/d/1IcBZ4yj4kJ14Gg0PVw3xbg-QqRYUQGUlHm8vVskgQOQ/edit?usp=sharing

- [ ] Download ACM at UCLA COVID Policy Spring 2022 as PDF and update the `Link to PDF `button to point to this new PDF.

**Comment by alireza-jahandoost** [comment]
Can I take this issue?

**Comment by matthewcn56** [comment]
@alireza-jahandoost sure!
