### ISSUE TITLE
Updates to ACM website homepage and footer. 

### ISSUE THREAD

**Issue by jainsujay02** [uclaacm/website#485]
Changes requested to `https://acm.cs.ucla.edu/`

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/78530348/164119232-5d533338-d52a-4faf-82b1-9b481521576c.png">

- [ ] Remove `ACM Spring Officer Applications` banner. 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/78530348/164119268-9a21170c-db1c-4034-9ef8-491048afeac0.png">

- [ ] Remove the following links from the footer: 

1. Fall General Meeting 
2. CS Town Hall 
3. JEDI
4. TechGala

**Comment by alireza-jahandoost** [comment]
Interested

**Comment by jainsujay02** [comment]
Sorry, I'm closing this issue without any of the requested changes since we're anticipating larger changes and we'd like to wait for them. Thank you for reaching out and please don't hesitate to take on other issues!
