### ISSUE TITLE
Town Hall Page Update

### ISSUE THREAD

**Issue by jainsujay02** [uclaacm/website#493]
Changes requested to `https://acm.cs.ucla.edu/town-hall` and `https://acm.cs.ucla.edu/town-hall/f21`

- [x] Create a URL that replaces acm.cs.ucla.edu/town-hall/**f21** with **s22**. 
- [x] Replace the townhall image with the attached image. 
![cs_town_hall_v4 2_(1)](https://user-images.githubusercontent.com/78530348/165413474-da941131-17d4-42b8-bdbc-eb2f577964b7.png)
- [x] Replace `Upcoming townhall occurs.... please rsvp` with The upcoming Town Hall occurs on Wednesday, May 11th (Week 7) from 6:00 pm to 8:00 pm PT. The event will be fully in-person and hosted in the Mong Auditorium (in Engineering VI). There'll also be catered dinner after the event (you must fill out the [Town Hall Survey](https://forms.gle/vnjbSHsDC1AtpaRh8) to get dinner!)(. To attend, [please RSVP!](https://forms.gle/Xyremk5dJAqx53Ks5P)
![image](https://user-images.githubusercontent.com/78530348/165414230-b5adea19-f10f-48e4-a69c-cd386a7aa552.png)
- [x] Remove the `ask questions in advance` button and `Event slides button`
- [x] In general, please replace all surveys buttons and links with a single survey - https://forms.gle/vnjbSHsDC1AtpaRh8
- [x] In general, please replace all RSVP links with - https://forms.gle/Xyremk5dJAqx53Ks5P
- [x] Change `We use pre-event surveys ... are anonymous` to We use pre-event surveys to gauge students' opinions on diversity & inclusion, academics and curriculum, and teaching practices. The Spring Town Hall's focus is on your questions so we only have one survey. We use the answers to present problems to the CS department and guide the discussion. Survey responses are anonymous! We need to hear your voice! Please answer these surveys before the event.

**Comment by matthewcn56** [comment]
What should we add with regards to the Fall Town Hall for the Past Town Halls section?

**Comment by jainsujay02** [comment]
There isn't any recording for the Fall Town Hall, but I think we can add the Fall Town Hall slides.

**Comment by matthewcn56** [comment]
Is there a picture from the event in fall we can use?

**Comment by jainsujay02** [comment]
yes, here's a link to them https://drive.google.com/drive/u/0/folders/1fVPPbAstNzrjGM71d6LqOqzKJB2r5mAh

**Comment by matthewcn56** [comment]
Is there a blurb about it you want to add as well

**Comment by jainsujay02** [comment]
In our Fall 2021 Town Hall, we continued the conversation on critical issues, such as inclusion and curriculum reform, with the CS department while empowering students to share their concerns with professors and the department's leadership.

**Comment by matthewcn56** [comment]
Is there a link to the event notes as well @jainsujay02

**Comment by jainsujay02** [comment]
https://docs.google.com/document/d/1vA0i6q_fU3DkulQwdYnslZIg0n7LsgckagGYsa8vv1Y/edit#heading=h.7k1pzoizjr9d - sorry, it took me a while to find these

**Comment by jainsujay02** [comment]
Also, the link for the RSVP seems to be broken not sure why but here's the replacement https://docs.google.com/forms/d/e/1FAIpQLSctUxnnNVc-HB2I5hAhfJOp6Ga4-YjayIiZp0s01607Z8Y7qg/viewform

**Comment by matthewcn56** [comment]
I've been using this that works https://tinyurl.com/22town-hall-rsvp

**Comment by jainsujay02** [comment]
One minor correction please: the form summaries and slides button isn't linking to slides for Fall 2021

**Comment by matthewcn56** [comment]
> One minor correction please: the form summaries and slides button isn't linking to slides for Fall 2021

Should be fixed now!
