### ISSUE TITLE
Updating Footer Of The Website!

### ISSUE THREAD

**Issue by matthewcn56** [uclaacm/website#504]
Inside our `Footer.js` file, we can update the footer of our page with updated styling and make it smaller overall!

Some overall things that people said about the footer that you can try to implement:

- [ ] Button to go back to the top
- [ ] On right side of footer, condense the committees into a singular link to the [committees](https://www.uclaacm.com/committees) page.
- [ ] Remove redundant information in the middle section (about, committees, events) as they are already present

**Comment by harveyzzhao** [comment]
got it!

**Comment by jainsujay02** [comment]
@matthewcn56 Are we still thinking of using the footer as a sitemap? If yes, it might be helpful to break the footer into an about section, an events section (Town Hall, GM, Tech Gala, Events Calendar), and a get involved section with mailing list social media icons, membership portal, etc. This is just an idea, so feel free to do something different!
