### ISSUE TITLE
Update Townhall Page

### ISSUE THREAD

**Issue by jainsujay02** [uclaacm/website#560]
- Add a link to the [fall 2022 townhall slides](https://docs.google.com/presentation/d/14MIk1bzHHr5b11cgYX_kAz5WQa6ToKD_9nnj3_5DLco/edit#slide=id.g18865745ceb_0_0)

- Update the Spring 2022 Townhall design with an image from [Photography](https://drive.google.com/drive/folders/1mKffx3Q9p0p6DXQMguY7EF6iZx41N2gX?usp=share_link)

- Add [notes](https://docs.google.com/document/d/1JTFaP27OsqA0sBhjbIC4mIzjCgqRLJyBxvOQ5FSrPCk/edit) for the fall 2022 townhall

**Comment by avaasmani** [comment]
Also remove Town Hall RSVP/Survey Banner
