### ISSUE TITLE
Update 'In News'

### ISSUE THREAD

**Issue by jainsujay02** [uclaacm/website#561]
- We won the outstanding chapter excellence award for our website. Let's proudly display it. 
- Here's the [link](https://www.acm.org/chapters/student-chapter-excellence-awards) to the official award from acm.org
- Please feel free to submit a design request for a graphic to add the award

**Comment by avaasmani** [comment]
Please have the post resemble the one made for our 2021 award, you can link it to this article written by the department: https://www.cs.ucla.edu/acm-at-ucla-receives-student-chapter-excellence-award-for-outstanding-chapter-website-from-acm/
