### ISSUE TITLE
Use of "here" for committee links is inaccessible

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#93]
On the [committees page](https://acm.cs.ucla.edu/committees), we use `react-anchorme` to automatically insert `<a>` tags with `"here"` as the target text. This is not a bad solution, but is not particularly accessible (nor is it good for SEO); `"here"` isn't really descriptive of what the link text represents, and is particularly troublesome for screenreaders. 

I think there are a few options we have:

* directly embed the `<a>` into the `.json` file that renders the component; given that this is a JSX object, this is totally fine, and probably the easiest way to do it.
* run the text input through some sort of markdown generator that spits out HTML. requires input sanitization
* use an icon to represent the actual link, and then use an `aria-*` attribute to describe what the link actually points to 
* something else I may be missing!

Let me know what y'all think!

**Comment by changyang-liu** [comment]
React-markdown (https://github.com/remarkjs/react-markdown) allows for parsing of markdown, and includes the option to ignore all HTML tags and also only allow certain markdown tags. It might be overkill if we only want to do this for anchor tags, but it would also allow for the use of other types of markdown syntax like bolded and italicized text. If you think that this would be a good solution then I'll give it a try.

**Comment by malsf21** [comment]
Definitely one viable approach! 

> If you think that this would be a good solution then I'll give it a try.

I'll defer the final decision to @vohndernet since she's the lead on the project! It's probably good to consider the balance of adding on dependencies versus the end user (ex who is actually going to be adding the links).

**Comment by vohndernet** [comment]
I do feel a bit hesitant of adding another dependency to address an issue with a different dependency, but so long as it doesn't further complicate the process too much when we update the Committees page in the future, feel free to go forth with this approach. I do like the added benefit of having other markdowns, at the very least!

**Comment by mattxwang** [comment]
I agree dependency bloat is bad! I think if we implement @changyang-liu's suggested solution, we can then remove the `react-anchorme` dependency 😊

**Comment by mattxwang** [comment]
Just to follow up from today's meeting; for now, let's just include the JSX directly into the JSON file.

For example, Design's "Styleguide Update"

```jsx
{
  title: 'Styleguide Update',
  image: {
    src: '/images/committees/design/styleguide.png',
    alt: ''
  },
  desc: '...Check it out design.uclaacm.com and the Github github.com/uclaacm/Styleguide'
},
```

to 

```jsx
{
  title: 'Styleguide Update',
  image: {
    src: '/images/committees/design/styleguide.png',
    alt: ''
  },
  desc: <p>...Check it out at <a href="design.uclaacm.com" target="_blank" rel="noopener noreferrer">design.uclaacm.com</a> and the <a href="github.com/uclaacm/Styleguide" target="_blank" rel="noopener noreferrer">Github</a>.</p>
},
```

We convert the string literal to a JSX element (`<p>` is probably the correct semantic choice), and embed an anchor with an `href` and relevant external link properties!
